# Generated by Django 4.1.7 on 2023-03-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sur_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
